url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Josefina Gilardi" # the name of your site, e.g. ACME Corp.
baseurl: "/gilardi"
url: "https://corvalan.dev"
description: ""
portada: "assets/portafolio/ladyofsituations/Lady-of-Situations-14.jpg"
collections_dir: "collections"
collections:
  obras:
    permalink: /work/:title/
    output: true
  colecciones:
    permalink: /project/:title/
    output: true
    sort_by: year
defaults:
  - scope:
      path: ""
      type: "colecciones"
    values:
      layout: "coleccion"
  - scope:
      path: "assets/portafolio"
    values:
      image: true
